### ISSUE TITLE
Might it work with Test'em?

### ISSUE THREAD

**Issue by PhiLhoSoft** [taylorhakes/painless#18]
I see:

> Browser Support
> Tests can run in browser with karma-painless

I (re)discovered [Test'em](http://tobyho.com/2012/06/24/testem-interactive-js-test-runner/) ([on GitHub](https://github.com/testem/testem)), which says it can work with any testing framework:

> If you want to use Testem with a test framework that's not supported out of the box, you can write your own custom test framework adapter. See customAdapter.js for an example of how to write a custom adapter.

Do you know if such adapter already exists for Painless? I think it can be a powerful combination.

**Comment by taylorhakes** [comment]
I haven't heard of test'em. There isn't an adaption for Painless. If you would like to create an adapter, I would really appreciate it.

**Comment by PhiLhoSoft** [comment]
OK, I might try... someday, when / if I have time. Another one to add to my todo list...
Meanwhile, I close the issue, will update if I get somewhere.
Thanks.

**Comment by taylorhakes** [comment]
@PhiLhoSoft I can look into creating a testem adapter. There is already one for [Karma](https://karma-runner.github.io/0.13/index.html). Karma appears to be very similar to Testem.

Here is the [adapter for Karma](https://github.com/taylorhakes/karma-painless)

**Comment by PhiLhoSoft** [comment]
If you have some time to spare and to spend on this, great! Having an adapter to another test harness can only benefit your project, anyway.

I use Karma at work, I wanted to see how Test'em compares to it, but I have (not yet) a compelling use case. As said, will try if you don't beat me into doing it... :smiley:
