### ISSUE TITLE
test.afterEach() not called after a test that throws

### ISSUE THREAD

**Issue by af** [taylorhakes/painless#19]
I'm finding that afterEach() is not invoked after any test that throws an error. I haven't dug into it yet but thought you might have better odds of tracking down why.

Below is a test case that reproduces the problem ('after' will only be logged once):

**Edit** the problem is also present when a rejected promise is returned in the test (see the last test case)

```
const { createGroup, assert } = require('painless')
const test = createGroup()

test.beforeEach(() => console.log('before'))
test.afterEach(() => console.log('after'))

test('failing test', () => {
    console.log('this will fail')
    assert.strictEqual(1, 3)
})

test('passing test', () => {
    console.log('this will pass')
    assert.strictEqual(true, true)
})

test('promise rejection', () => {
    console.log('this will reject')
    return new Promise((res, rej) => rej('asdf'))
})
```

**Comment by taylorhakes** [comment]
Thanks for reporting. I just recently ran into this bug as well. I will fix it this weekend.

**Comment by taylorhakes** [comment]
This is fixed in https://github.com/taylorhakes/painless/releases/tag/0.9.5

**Comment by af** [comment]
Working great, thanks!
