### ISSUE TITLE
Add test isolation

### ISSUE THREAD

**Issue by taylorhakes** [taylorhakes/painless#8]
AVA has a great feature where all test run in their own environment and don't affect each other. Can this be done without adding subprocesses or threads?

**Comment by af** [comment]
Maybe the [node `vm` module](https://nodejs.org/api/vm.html) could be used for this? Although it looks like you'd need to create a context to expose the full global environment, like `console`, `setTimeout`, etc. Not sure if it's an appropriate fit, but it's a thought.

**Comment by af** [comment]
Here's someone talking about a similar approach: http://stackoverflow.com/a/10869838/351433

**Comment by taylorhakes** [comment]
This looks promising. Thanks for the information. I will experiment with it this weekend. My only worry is that it will make debugging more difficult.

**Comment by taylorhakes** [comment]
I took a look at the `vm` API. Unfortunately it works a lot like `eval` in that it operates on strings. It makes debugging very difficult.  I don't think that is the right path for painless.

I originally thought that AVA created isolation for each test, but found out it only isolates each file. It is not as good as isolating each test.

--async in `painless` is probably the best alternative for now. It will force tests to not depend on test order.

What do you think @af?

**Comment by af** [comment]
Yeah I wasn't sure if it'd be suitable, but it came to mind so I thought I'd mention it. Parallel/async test running isn't really something I've thought too much about, so I'm neutral/ignorant about the best approach for it.

**Comment by taylorhakes** [comment]
Ok, I am going to close this for now. If you or anyone else has ideas, we can open this again.
